apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:qzDAZyfmRzfzcB6fIwrMsFX4ZHLq5BAkzzFcx/bm01rczzn9D41IIg==,iv:W3s3a26LOPYhnnyYQ9S5q/CPf0h+GnwY7mahcMMWYOk=,tag:bcncRcW9UmS924BwWZaDgg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1acpaftp92yxuuku8j3ndeppcgww0h5zhwgy80jh3933w93xp5cwqrze397
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNEhDQy9hem1zYkduRHVz
            USsvVHRjNXlIb0hEVnhMdVY4UEtOQWRHb2xrCnkxRE0wQ0Zkc2NtWUxEZXBGSkdO
            anBWTnF0SVZkcXJha0tyVHBQMUZyTXMKLS0tIGVyYWJKMFpwdXR4WlhleWZNUmpZ
            OTdFUm1JWndJUk1BMncyQy9lemU5dm8K7eMbBeR+VYt4x82t8rg0+8s1PrrEqdYF
            Q5gELG1QULTR+R6U4sTxEkwB/TiHXJiultHHfT9CGSoQ7GUS7brCmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-14T14:27:52Z"
    mac: ENC[AES256_GCM,data:96tYkL45PCxAvOA04oUzFGv8SD8g3bmCve7Rhp1iIa4nC43dQd0ufDdW7jkjFBsoYJXLNZBNchueEJqcIi0wMG5qvvJ3y8RFXqIQJIajiS5hFL/acUtxQgHDA/C73d3ZTN0TId2+Qyeb8ObtqBLF5HMBLkkvNrOcVB9ocS1bg+o=,iv:Anh5wnIFdSpUObjMZejNqytvewB94PnhsC9/RnDRsnc=,tag:BINGqihtGSLQ3mG4O2P62Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
