apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:tHMg2HXLoJ2kkGML6wRU/NUCmqu12LqooqhfRoEWEZTNpQDX/2wxOQ==,iv:+mUZiJBixXlPbwnYU0jcQTVHdXgUtZHzcvLoLn5grto=,tag:kNwpqoHxFkXNcH/fzTDJfQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1acpaftp92yxuuku8j3ndeppcgww0h5zhwgy80jh3933w93xp5cwqrze397
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZHlGUDJobFdMR3F4NWVL
            dnVldzBoNUlJY21QMGFNL1d3d29ZdWVSclhVCklmQ3RVZlZQMEtPV2IxTEJPM3dv
            MHpSRmNkbnlHZ1I5a3QrcitXNnR2bXMKLS0tIHZUaU9MTzBBbTRSbTQvbUh3eDd0
            UWpTVkw2ZUFLNUZiQnc5MkpwcGoyZWcKgfeBiYrTVxbQQsCUZsBXt8o0Pu1k7MZS
            oE4XW+5AqHxeQTrhAnSVETlHMyYH9YlhLuUzP3cf3M06AC7aua+pGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-12T22:38:27Z"
    mac: ENC[AES256_GCM,data:TdH2S2Tvs7rWu/Pt9poxOcWr1Afkh5cyWUM1/2mWsepKZ9Gjxe7fWidmiKZ61M75NaKHAm9JbnWEtj9PULL67pF6bcDIQxxJHBJwwW5e60riMZ/R3fnhJeTX+ZbsC0y/nqRygj/6ulheOninwDLlplQhAHl6mkzibY71SW6O1x8=,iv:pEoMn+lRlVoFjPGwtOJIYVDF4nMohFKvIX/BDZOEf5Q=,tag:+Fcyp08cWgiVDrjab5f16w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
