apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:U0h5/chPThBmkiYTbRtHgT5mQFbbdpSvr1MqtUG7oEDUkeYCbBr3LA==,iv:yMezmldpxcw85b74cLf6EKSZOUEopi5hUKsmsjmcw08=,tag:J++jdOMsdQMpNOlhQMU4WQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1acpaftp92yxuuku8j3ndeppcgww0h5zhwgy80jh3933w93xp5cwqrze397
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyL3RORnBTVGp6ekl5bE9j
            RW1sWnZzOExSRWUra1c3c3ZJNnBwKzVndzNFCjVYR09PTEZ5MHd2WHBqak1hZ0pz
            blFGTnJkR2FCdlZnRVMxRUVqb0tybmsKLS0tIHAxOVFtb0FpUjFCTk1FQ1h0ZVZP
            dWdDM3hHL3FRa25aT1lUTnUwMXZ3OUEKDSMm5Tbsf/cZE6/jopfK8EY9wA5fRZvW
            Uj3EyB/i7boCzx30pc8V42XTuGovSHZhn1YNmmgK7e3yiERZLbhPdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-12T22:31:02Z"
    mac: ENC[AES256_GCM,data:raqJKIu3KtxrwuJ846wXXDHrcsavgbpFGU58tXYM1IGTVU0nnd49CAbVPDi5nQmsTQGOzDob6nRE1owMqsFpUXWCmaRgOZafsXzRtjZrmaFZTdMC04P6V9B4ooGFk7omwVUzXQZLN1afdhfq3ncNPlWA+0L+PXzh7b1dgCLAaWE=,iv:auU1lOnB+tUqB47tA2cCfhut54K82WX0mkyW6LEOz6U=,tag:MXLpaxayILpa/INKJFw2cA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
