apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:WOjSHZMwUzlBu6FPffYE+tAi71IDNfKUGbZ6LANQJ0HrPKxYSOPbWw==,iv:OT9Y27TVSwAdKkE/FSGtqOeng3KyNTRlklLIkG6RDZM=,tag:cbGQbriTPCDBPC3WhHtgWA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1acpaftp92yxuuku8j3ndeppcgww0h5zhwgy80jh3933w93xp5cwqrze397
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQ2o4a0VaeEFpbDhZK2Zz
            MVkzS080YUNNMWNaTlhWbjVUUENNSnBoTnlrCnBwdjQ0RnNUeEtMcmVRdGswRVht
            T3RjSHcwT3l5WHBqK0poRmFNcGtpcE0KLS0tIDMza1dWd0hDR2ZiQUhiVGYwMGpm
            eUNiY3d4SjJhOGo2RVcrVXl3aFF1S2MKa2RmI3azq9AQY/6dQJ/qv4276dzmgBQf
            UfQfQpFeLHDT/nXQYa6QfzuV1joWMMmxlA9Ks75TVOrhlm+elE9wFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-12T22:57:26Z"
    mac: ENC[AES256_GCM,data:t4MEJsf5IuNnrE6nMMHmxiyQlOQFpHhmn3v6DxWGjlJg17A18JNwxs0l6Uj6cOcxoAkIEYuwJ952mNTD3nvrOadtI/CEacK2Fee4w3LMOpTaCkd60zsAITSgudKhjH1TLQRImOCB0Ogm2jzdE/za1F5vGgx8kEBJJcz/e16mU4U=,iv:7LHRxn/f10n/b6REhULAV8qw4BVxJjk0LI7RU7KD0sY=,tag:9IHIzcqQx4m2FTVjBk5oeQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
