apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:v/nU/AqEf/q3zfnrrS/FRxjT5R/KP9dKZPzaJC85TpJcV3proKIKyA==,iv:bQ5yVDezVgbu8xjn+9NvhbdpITCvh8tsX8yRzWVpq2M=,tag:va4QxwgltGvX1QbHWc5tOg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1acpaftp92yxuuku8j3ndeppcgww0h5zhwgy80jh3933w93xp5cwqrze397
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZ1ZhM3RYUGNJejQyV2xJ
            aFM5Z0RuM1lSVUhXWWlsdyszUWFjN1ZFK21zCnNqSUx5a0tEczRPL3YxQnN6VVYr
            STJEQTg2YVNtR1RqVG1VQkpkcDMwQjAKLS0tICt0bFlkMDB3UEhrZklLUlFQVEwx
            a21WMkg2Smw1K3dHMUVxeW10Ui9xeWMKZ5XjU6oDwn02lYvpqWK8oh5x8gxjLPX/
            uyaGTzZbg9BBwG5EegJGJctzBsx2SpzJhyuf7rdNtwP3WAHPzFNh7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T10:16:50Z"
    mac: ENC[AES256_GCM,data:vp5EmwtJgrzLVdbN+LHWhMvjnAI7OkhYM3d+/Yf3fFaoKKfKa1sugDQvXCOU/2lVdrbm42O/w6AxoG2cH5mOpP0HDMxIIWmoQ+gUOfmSvG0WAyH7L7Tn6lWNiOOSN8fBKKPFGgJGA4A03tmvTkI1LZuXMmbyqmaVDeRh7FTGcQA=,iv:+mHRG8clETFj47m8T0++tL/p7I500UObSlJMlbYHczs=,tag:QRLaZILf6lL9ZQLfdREB1w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
