apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:OqlFlwuzbPBYpskv4TI/Z5XZ3cyGCJQGSt1UKAXKJbayfgnrGEcKIg==,iv:qs/gcch/qWcYpTt1KSntWxfuuR8N+2FfJ+JeTUIMzfs=,tag:x4LhDFctKG/US21+IcvliA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1acpaftp92yxuuku8j3ndeppcgww0h5zhwgy80jh3933w93xp5cwqrze397
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVzhqZDRJWXd3V08vLzFB
            SDI5NGpHdU5IOTJ2bEJ0U1ZySFZYVjhnZUZzClJxdDhNaWVOejRPM0FIcmJEcjg2
            cERuRWRBK1Q4aFBvYi9Xd0ZRLy9XcHcKLS0tIEgvenoybW96M01qSGpzQ21IWWlx
            elpuMDI0eEc4OElnZCtjWm55RnhkcTgKc02qJdozgfmpW0QL9Gd+1I2lqQupoAeB
            cZVoIp4Rpdf+MLufPt8h69NAeVfLEJM83MtctUaWg3u0Pdx8pP4eVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-12T22:15:55Z"
    mac: ENC[AES256_GCM,data:mPeYVxG0keNSKgiKgbix1sP+agathZhiHiNovf81R4buJiyL5y97iFV7AZrKChwjHpWqzlTUV4fKMfZWzknisH2ofjFL0CotvRtCC1kTWZl9VBYwm+yQovL1WLZKrX2emrX/tjy1EvoRPbbsqMC5hNjadPQHcdZ4F2tuquP0O4Y=,iv:PrEGA/yZd6QrIs6VfPBaebtMSjfdHC1s5Ey0HF4kflk=,tag:v57hEAOMlhlw01bAr6AcBA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
