apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:jPnN6IFszUv14RMnq9jl7pxtYcn6xuYcz4R487W5d9LvP5MKdW4m7A==,iv:p0VdR1XnQia5QWpkv5wiaoaembEJYUVs2NeYaqgUDUE=,tag:0ndOA4axoDnQ+FSjfUjn2w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1acpaftp92yxuuku8j3ndeppcgww0h5zhwgy80jh3933w93xp5cwqrze397
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZjI4ZDB6SUJOM2tsK1h2
            UTZvM0lpbEFZRjE0VEhRSXZFemtWejhMQVFzClZGSjNZSm84dk9QZUp4WUNvUEl0
            NURYNXVrRmNjTXVaVXdKWHhLK3VldkkKLS0tIHh0QldLaUd4dFNwMURSd0FNKy82
            MUhndEEvcjBnOTFMUkZiNkpXdVlYNGcKufKQA2kmhh4bK4fxeV3kRi0JE303O6dI
            2i7ZCpXPIeD9hGT+y5muT2WqviSli2UcthPrFZSP2lzadu0IeHsacA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-12T22:42:03Z"
    mac: ENC[AES256_GCM,data:Kwfk8PPSkLwCtYi6mzHe/RG2fjCPAVt4LckGc9lAnn1RoUMzo/psXyKy6QPj5HX4DtxafjoyLkyGJ/4B+w2N5sGTh7ovXTlNvmnBSEZ0mcj6kxvoV73qr1s6q8G5OALx8O+rtr/IAQfn9NvOufE+r0lfbm1uMkAmpBz0xn14rmc=,iv:8p0i3+S7gkK/1j2q+oX69mLmpC5npqXb148UFC2jidY=,tag:vkAWqb+xyy2qq+zEabC9uA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
