apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:4fqRhRamYIuo8asTIN19Rps2zsgOrC/y76HcBN0ddPnJd7CiPz7PyQ==,iv:oqmAiMneKqhfAguuCFTAewTmjQrhZ7sI4d1oc6Qp20Y=,tag:r+68g0YF/IZluCNmXX4USw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1acpaftp92yxuuku8j3ndeppcgww0h5zhwgy80jh3933w93xp5cwqrze397
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WFlIMEtObkMxc0N0Tkxq
            eU5Rb09ubHJJb2QxNDJWYUY4My9uNE5aQkdjCkN2Vk1VOEtPTlg5bXNoME94TUww
            bk52OGpCd0NSeFduSVFIdERDMDNCeHMKLS0tIHBGNzVCN0Jxd3hzbnp3SHNuNjVt
            WDJVVnhSSXJQS1l0bno1NStveGF6Y2sKfxUKw0xwZb+vbcumS7BEFwNT1QfMx9+x
            ozwkPqLrDQ1Qbw+XREYhasmTU5AIbZftdLYJt73IH2GIOPXkurBK/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-07T10:10:21Z"
    mac: ENC[AES256_GCM,data:h086r7EdocR09QWb9gMWRbV0/bV2+ABKpbeGUoRneVEENo3Cf8mdkUtIv5fJnnFlup/uMMSukPYUxb8BdosbE31lLXwylKAZxdHLbAj4htumPmyQEmrKm+CiB/a+8RWVuZ7+d2Ca2trYgtAPDuOLlSNTGlDLoQA2ROrXSESFG04=,iv:2ZGfVWeTEas+D5ONf7nAg6U4zZgmx1SaJAtFdbWt3a8=,tag:CET1dOivrxmwZJqRLep9GA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
