# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8tz
  namespace: k8tz
spec:
  interval: 15m
  chart:
    spec:
      chart: k8tz
      version: 0.18.0
      sourceRef:
        kind: HelmRepository
        name: k8tz
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    timezone: Europe/Brussels
    replicaCount: 3
    cronJobTimeZone: true
    webhook.certManager.enabled: true
    webhook.certManager.issuerRef.name: domain-0-le-prod
    webhook.ignoredNamespaces: ["kube-system"]