---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: krusader
  namespace: krusader
spec:
  interval: 15m
  chart:
    spec:
      chart: krusader
      version: 8.4.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false    
    TZ: Europe/Brussels
    resources:
      requests:
        cpu: 10m
    credentials:
      s3:
        type: s3
        url: "${S3URL_minio}"
        bucket: "${S3PREFIX_minio}-krusader"
        accessKey: "${S3ID_minio}"
        secretKey: "${S3KEY_minio}"
        encrKey: "${S3KEY_minio}" 
    persistence:
      containerpath:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true                          
            src:
              enabled: true
              trigger:
                schedule: 0 3 * * *
      datapath:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true                          
            src:
              enabled: true
              trigger:
                schedule: 0 3 * * *                  
      homeds:
        enabled: true
        path: /mnt/main/HomeDS
        mountPath: /homeds
        server: 192.168.1.49
        type: nfs
      media:
        enabled: true
        path: /mnt/main/Media
        mountPath: /media
        server: 192.168.1.49
        type: nfs
      pictures:
        enabled: true
        path: /mnt/main/Pics
        mountPath: /pictures
        server: 192.168.1.49
        type: nfs
      vmstore:
        enabled: true
        path: /mnt/apps/vm_store
        mountPath: /vmstore
        server: 192.168.1.49
        type: nfs         
    ingress:
        main:
          enabled: true
          ingressClassName: internal
          integrations:
            traefik:
              enabled: false
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
            nginx:
              enabled: true
              auth:
                type: "authentik"
                internalHost: "authentik-http.authentik.svc.cluster.local:10230"
                externalHost: "krusader.${DOMAIN_0}"  
          hosts:
            - host: krusader.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix  