---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 15m
  chart:
    spec:
      chart: tailscale
      version: 10.14.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values: 
    global:
      stopAll: false
    TZ: Europe/Brussels         
    tailscale:
      authkey: ${TAILSCALE_AUTH_KEY}
      auth_once: false
      userspace: true
      accept_dns: true
      routes: 192.168.1.0/24
      dest_ip: ""
      advertise_as_exit_node: true
      