---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik
      version: 33.11.8
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:    
    global:
      stopAll: false
    TZ: Europe/Brussels
    resources:
      requests:
        cpu: 10m
    credentials:
      s3:
        type: s3
        url: "${S3URL_minio}"
        bucket: "${S3PREFIX_minio}-authentik"
        accessKey: "${S3ID_minio}"
        secretKey: "${S3KEY_minio}"
        encrKey: "${S3KEY_minio}"
    persistence:
      media:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true                          
            src:
              enabled: true
              trigger:
                schedule: 0 3 * * *  
      templates:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true                          
            src:
              enabled: true
              trigger:
                schedule: 0 3 * * *  
      blueprints:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true                          
            src:
              enabled: true
              trigger:
                schedule: 0 3 * * *  
      certs:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true                          
            src:
              enabled: true
              trigger:
                schedule: 0 3 * * *  
      geoip:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true                          
            src:
              enabled: true
              trigger:
                schedule: 0 3 * * *           
    cnpg:
      main:
        password: ${AUTHENTIK_CNPG_PWD}
        cluster:
          singleNode: true
        #mode: recovery
        backups:
          enabled: true
          credentials: s3
          scheduledBackups:
            - name: daily-backup
              schedule: "30 3 0 * * *"
              backupOwnerReference: self
              immediate: true
              suspend: false
          revision: "2"
          retentionPolicy: "7d"
        recovery:
          method: object_store
          credentials: s3
          revision: "1"       
    redis:
      password: ${AUTHENTIK_REDIS_PWD}    
    authentik:
      credentials:
        email: ${DOMAIN_0_EMAIL}
        password: ${AUTHENTIK_PWD}
      email:
        host: smtp.gmail.com
        port: 587
        username: ${GMAIL_USER}
        password: ${AUTHENTIK_SMTP_PWD}
        useTLS: true
        from: ${GMAIL_USER}    
    ingress:
        main:
          enabled: true
          ingressClassName: internal
          annotations:
            nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          integrations:
            traefik:
              enabled: false
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
          hosts:
            - host: auth.${DOMAIN_0}
            - host: "balazs-deemix.${DOMAIN_0}"
              paths:
                - path: /outpost.goauthentik.io
                  pathType: ImplementationSpecific
            - host: "tc.${DOMAIN_0}"
              paths:
                - path: /outpost.goauthentik.io
                  pathType: ImplementationSpecific
            - host: "christine-deemix.${DOMAIN_0}"
              paths:
                - path: /outpost.goauthentik.io
                  pathType: ImplementationSpecific
            - host: "frigate.${DOMAIN_0}"
              paths:
                - path: /outpost.goauthentik.io
                  pathType: ImplementationSpecific
            - host: "lidarr.${DOMAIN_0}"
              paths:
                - path: /outpost.goauthentik.io
                  pathType: ImplementationSpecific
            - host: "metube.${DOMAIN_0}"
              paths:
                - path: /outpost.goauthentik.io
                  pathType: ImplementationSpecific
            - host: "prowlarr.${DOMAIN_0}"
              paths:
                - path: /outpost.goauthentik.io
                  pathType: ImplementationSpecific
            - host: "qbit.${DOMAIN_0}"
              paths:
                - path: /outpost.goauthentik.io
                  pathType: ImplementationSpecific
            - host: "radarr.${DOMAIN_0}"
              paths:
                - path: /outpost.goauthentik.io
                  pathType: ImplementationSpecific
            - host: "sonarr.${DOMAIN_0}"
              paths:
                - path: /outpost.goauthentik.io
                  pathType: ImplementationSpecific
            - host: "syncthing.${DOMAIN_0}"
              paths:
                - path: /outpost.goauthentik.io
                  pathType: ImplementationSpecific
            - host: "pihole.${DOMAIN_0}"
              paths:
                - path: /outpost.goauthentik.io
                  pathType: ImplementationSpecific
            - host: "krusader.${DOMAIN_0}"
              paths:
                - path: /outpost.goauthentik.io
                  pathType: ImplementationSpecific            