apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:to3dL1lHmyOmDXb2rJcPWaZN/oHlItpLs+5mUamj+DSPPmL4C/dVfW3Ajac03Fn0Mvxivpi4w7vLU8QbUEe2YJUGbBBp7CsCQSsvxDdTL/ELShBwSk/rPj4HYGoI26RWIxyHbjJSG5PktMbLf++T9w1YtGhGYDcnDUnATkca2XidUVfSvQSMgVEZ24dvClGN6miMRTcWJLjq2YKz+OTXNKeXfS8lFTPW8+bAUmEn22pNL9dvQ20lyZgZteBjsXyrVqomVrB11ECvRMjVjQO5YiDZRiLErn12kNkcnQKlw+Nb/9Whg9X6kZIMPakt4uBOMitiOBjblJWppdrZEYkzufvXia66Cq3ysWKIW47NnwMLFKIcwJlFyr8kkp66tv0U,iv:TUA8T6RrfyXbaAXpW7Dl/0lZSZR/+Fi/nKWjskV4NVA=,tag:sZbM19tWZz6Xrv1YAPQrVw==,type:str]
    identity.pub: ENC[AES256_GCM,data:W3E6ZaT7/b1NSMNQzJdBOVMQ0txIMxrNd/EEU1bRNLg6q5Pf0BLdFjacYQ0aAaiIsz/9268w5NaH0famZR3FtircuGGd0Ki02MzpQcjnaJawDBjju4sV9v/21PmHxyOwMY/8/Ugs636y5aLmuUBsc3DYoMYdhv7fzjfFw0y3tgv51CUdd4jk20jI1SmZBMhEcvdUmpSvTIKbEEWFZ1RChyC22YMlCXYHFBMJFq5SvAOS1eND2j2qv+beUQ1wL9+6jTYeExRsF6d7yYCMdw==,iv:2DV+wwL8/7loYCmBZcKUn2X0TTrlf/Q774WTsFxdi9E=,tag:6vnevNc1JvznAaI3kMMCvQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:FEH7xq+GzdlaQMUorPewL0JSDPZ5M8RgtX9MfWPmk526jc6DnIHhE0guyNtME24LaJ4arvqkAwtzcaVDbKb+OdiHs2NH+wgiaueHdxQzNLY+1yr6HNEIBWWKD1nShm5YEtxlazaBUFqp2c8fh1N0ZykCyoBu2ZXo2Wtp1ScRedlNOygQY6DoPHfEgT4XBwdxqaWpBR8HRHd4Zx1tFnRkaDJKJ9wg6asAD8Uu,iv:Dl7A5SuLAii/1WRNsFusIzVQV/QTkzQUL0rO7SdJfv8=,tag:RBEbVFBJIytU43cOIMQmaw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1acpaftp92yxuuku8j3ndeppcgww0h5zhwgy80jh3933w93xp5cwqrze397
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQnRRdElncW1IWVVGRGFl
            OW8yQTZJSEpQU3ZEYVZzZm14amVPUkYxYmxzCm93SWJ3aS9XNFpqQnRhUVlLdW9Q
            THdVZ2FOcTNVMGsrRFI2enExczJKSEUKLS0tIEJsMFM0N0R3NTFaUHc2bmwweUtO
            ZCtBV21SNzBJbEdHbGdVK3NnejdWNEkKxFQX6MitFmbIn89o4sXmXJQ/ErurBClf
            5OZ/qabZNNrPCoYYsQs53vjR3J1tot1blG+qayRZs900AG5x76bdrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-14T14:27:52Z"
    mac: ENC[AES256_GCM,data:jtSPjNxuJqBqsk67EpAgfst+5zVoilPl/PyyRlAwOOf9zorZMIWvDpOZMF92LhbNFJteQlwkd40VcbnNPHtRQaO91v505r0rQL55zgKBxxMAo70omVe2Hp5tCqXyC85XuhBw6QsGbUQ2xKHMBZHnIjgYd/SDFRp6oKqe/ZMtaSM=,iv:mw1XPfb6K5haELEzXmKSbIQ/QUXQCeS+gsdJ6n/DaEQ=,tag:peNmYakNyTEfEYMVOP3NpA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
