apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:iZTo/nOe52X3u9b3rEzo3pSrNih5Xau6R7F6GVsSQudh2dm3+wp9wMJmYK5SfBzICj/75mwxnaaMwg8UeSSf2G/Xt9u5a23qVLnq9HBDV/yIaFhWwcwYphH26CMDUEa8eX6RptUuJSeFXoJMKoKFNIIfpmdo6L7ktLHTOrWnzCMEdLh/9Vp1Bb9va415XRH7xWHL4tJJh2MZu6YCNVF9LHn2XMqEHYQ486jJ/9HdA1NwF1amD5Jc96pr989+PhV5C9a7JodbSUIcOFNObYDgqb9lXFU9O+HAKlcYB1WYsM99bXmd/tWFgFxdoYyFPo6UG4ps4JZInK12AhL6qAd1xy+laHnhFS4agGhNHJ41oOCFq0c3vPlaSHNav1umMfQE,iv:nXgA/lXqcteSwc9bI9opEkkluur15uvRO2w+xLTdoyQ=,tag:BZJEDvKvRI0zBQOdsD0IPA==,type:str]
    identity.pub: ENC[AES256_GCM,data:DZTIfI19gEGuEMeZokJJDckfeSsDbog+8PLXurnekiUAa7Hj+n/UWd4k1tvcCTkuOUo8C0D723Gd+BAt75yBpMAJtAINTUyU2rboOp92Y4cfMR1/eiLdLPvZtU1466rBdVcfiUFIZUFMPXXCT4rIA6+y4r16CCFZIQP3w9N90Y6yW1mnvK2zbfZ0peyx0vrmf1IzXNyYoI9TlxEAJPjAN8h+pN6UUdUCl1gkcdtZ8htbb1XIvxhTcmwPihu68Ar/1kpvMdq1dJHy1vLZ3Q==,iv:VKBv24n31if88AZSmKdWu1zSN8dUeCbp3kJy7E27iA8=,tag:1RH1YUFNdfEwziKdPZWMGw==,type:str]
    known_hosts: ENC[AES256_GCM,data:x2XmMucYsCBaKSuOhkQ1RVQ31SfpjiBXrRNbTxXOP1Y8sm4yc1+UJ0MtY8r7yLRZKrsa3vQq4YyBKmhawkeRDui79p2Qozedkg/WWWfk02E8jgZPALUjBVBqm5qITHPoccn4buV4dIrhfsTFbxoVnQ5BdBk54Oyh8d6Mc6CjSV4BClhtdbdQiUYxjY311TpM6ShUhGWJgpqSwiE8yZ64R8UxAjEfvG7wfgTW,iv:cHbhKX9oLXWvpl4rELcdbW0XtdW0BFFKDFd938FFGL8=,tag:z726aC20dFju78tWO5dshQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1acpaftp92yxuuku8j3ndeppcgww0h5zhwgy80jh3933w93xp5cwqrze397
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOExiTW9NWndkSGIybDNV
            TmdrSzMxNytTOXlsRklPMEV1a3V3VzA3d1hJCmpCQ2VhTTh6Mjg3UHdHQmxPUDky
            M21BdVRuTmtURjZoSldacTZ3UmYzRjgKLS0tIEoxOXlIeWhCb2ttek8vbmFZYm9j
            MW9wWW05TjF1MmNtd1I0U3FiakNLUEkKRwZ5wAz16JX7rIUwRHGBzEqbH8MY1DeS
            YhmbmBAabx1eFQhQMrge8YAMznCyfHexHxAJT51yUDUU8tcdo+6Ddw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-12T22:15:55Z"
    mac: ENC[AES256_GCM,data:dustMHv29meLd/uer5Opt1btiV5t9iQt+5agN5bXlJIHnukXblRH9H1++xhYWKJQK9m0wzU28pxzaWRYTMLZkZYm8tj96SrLn62p25bf/PFjCpLRuHoljvdZH/7lmC8mDeLJXd/q+9oVLcAvci1xaku+nl7I3wgpQ0fbHmIE9YY=,iv:dZbUNICuaQsvgLYuPFfCO28ATwyf+H27zFhBk1iheGw=,tag:+Fy8nV7rQEFc6lrlm8Jo8g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
