---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent 
  namespace: qbittorrent
spec:
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: qbittorrent
            patch: |
              - op: add
                path: /spec/template/spec/containers/1/resources/limits/squat.ai~1tun
                value: 1
  interval: 15m
  chart:
    spec:
      chart: qbittorrent
      version: 22.5.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    TZ: Europe/Brussels
    credentials:
      s3:
        type: s3
        url: "${S3URL_minio}"
        bucket: "${S3PREFIX_minio}-qbit"
        accessKey: "${S3ID_minio}"
        secretKey: "${S3KEY_minio}"
        encrKey: "${S3KEY_minio}"            
    service:
      torrent:
        loadBalancerIP: ${NGINX_INTERNAL_IP}
      #gluetun:
      #  enabled: true
      #  name: gluetun
      #  ports:
      #    gluetun:
      #      enabled: true
      #      name: gluetun
      #      port: 8000
      #      protocol: http
      #      targetPort: 8000
      #  type: ClusterIP    
      proxy:
        enabled: true        
        ports:
          gluetun:
            enabled: true            
            port: 8888
            protocol: http
            targetPort: 8888
        type: ClusterIP           
    persistence:
      config:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true                          
            src:
              enabled: true
              trigger:
                schedule: 0 3 * * * 
      downloads:
        enabled: true
        path: /mnt/main/Media/downloads
        mountPath: /media/downloads
        server: 192.168.1.49
        type: nfs
      qbitcompleted:
        enabled: true
        path: /mnt/main/Media/downloads/completed
        mountPath: /media/downloads/completed
        server: 192.168.1.49
        type: nfs  
    addons:
      vpn:
        type: gluetun
        killswitch: true
        excludeNetworks_IPv4:
          - "192.168.1.0/24"
        excludedNetworks_IPv6: []  
        env:
          HTTPPROXY: "on"
          HTTPPROXY_LOG: "on"
          HTTPPROXY_LISTENING_ADDRESS: :8888
          DNS_KEEP_NAMESERVER: "off"
          DNS_ADDRESS: "103.86.96.100"
          VPN_SERVICE_PROVIDER: "nordvpn"
          VPN_TYPE: "openvpn"
          OPENVPN_USER: ${OPENVPN_USER}
          OPENVPN_PASSWORD: ${OPENVPN_PASSWORD}
          SERVER_COUNTRIES: "Belgium"
          FIREWALL_INPUT_PORTS: 10095,8888
    ingress:
        main:
          enabled: true
          ingressClassName: internal
          annotations:
            nginx.ingress.kubernetes.io/auth-url: http://authentik-http.authentik.svc.cluster.local:10230/outpost.goauthentik.io/auth/nginx
            nginx.ingress.kubernetes.io/auth-signin: https://qbit.${DOMAIN_0}/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri
            nginx.ingress.kubernetes.io/auth-response-headers: Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid
            nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Host $http_host;
          integrations:
            traefik:
              enabled: false
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
          hosts:
            - host: qbit.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix        