apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-delete
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 20 2 * * *
  groups:
  - default
  name: delete
  retain: 0
  task: snapshot-delete