apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: trim
  namespace: longhorn-system
spec:
  timeZone: Europe/Brussels
  concurrency: 1
  cron: 40 3 * * *
  groups:
  - default
  name: trim
  retain: 0
  task: filesystem-trim