---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metube
  namespace: metube
spec:
  interval: 15m
  chart:
    spec:
      chart: metube
      version: 16.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    TZ: Europe/Brussels    
    resources:
      requests:
        cpu: 10m
    persistence:
      config:
        enabled: true
        mountPath: /config
      downloads:
        enabled: true
        path: /mnt/main/Media/temp
        mountPath: /downloads
        server: 192.168.1.49
        type: nfs
    ingress:
        main:
          enabled: true
          ingressClassName: internal
          integrations:
            traefik:
              enabled: false
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
            nginx:
              enabled: true
              auth:
                type: "authentik"
                internalHost: "authentik-http.authentik.svc.cluster.local:10230"
                externalHost: "metube.${DOMAIN_0}"  
          hosts:
            - host: metube.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix