---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
spec:
  interval: 15m
  chart:
    spec:
      chart: paperless-ngx
      version: 11.2.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false    
    TZ: Europe/Brussels
    resources:
      requests:
        cpu: 10m
    credentials:
      s3:
        type: s3
        url: "${S3URL_minio}"
        bucket: "${S3PREFIX_minio}-paperless3"
        accessKey: "${S3ID_minio}"
        secretKey: "${S3KEY_minio}"
        encrKey: "${S3KEY_minio}" 
    persistence:
      data:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true                          
            src:
              enabled: true
              trigger:
                schedule: 0 3 * * *
      consume:
        enabled: true
        type: nfs
        server: 192.168.1.49
        path: /mnt/main/apps/paperless-ngx/import
        mountPath: /consume
      media:
        enabled: true
        type: nfs
        server: 192.168.1.49
        path: /mnt/main/apps/paperless-ngx/media
        mountPath: /media                     
    cnpg:
      main:
        password: ${PAPERLESS_CNPG_PWD}
        cluster:
          singleNode: true
        #mode: recovery
        backups:
          enabled: true
          credentials: s3
          scheduledBackups:
            - name: daily-backup
              schedule: "30 3 0 * * *"
              backupOwnerReference: self
              immediate: true
              suspend: false
          revision: "2"
          retentionPolicy: "7d"
        recovery:
          method: object_store
          credentials: s3
          revision: "1"
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                PAPERLESS_ADMIN_USER: "Balazs"
                PAPERLESS_ADMIN_PASSWORD: "${PAPERLESS_ADM_PWD}"
                PAPERLESS_ADMIN_MAIL: "${DOMAIN_0_EMAIL}"
                PAPERLESS_CONSUMER_POLLING: "5"
                PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE: true
                PAPERLESS_OCR_LANGUAGE: "eng"
                PAPERLESS_OCR_LANGUAGES: "eng"
                PAPERLESS_URL: "https://docs.${DOMAIN_0}"
                PAPERLESS_CSRF_TRUSTED_ORIGINS: "https://*.${DOMAIN_0}"             
    ingress:
        main:
          enabled: true
          ingressClassName: internal
          integrations:
            traefik:
              enabled: false
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
          hosts:
            - host: docs.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix