---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 15m
  chart:
    spec:
      chart: pihole
      version: 20.1.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false    
    TZ: Europe/Brussels
    service:
      dns:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${PIHOLE_IP}     
    credentials:
      s3:
        type: s3
        url: "${S3URL_minio}"
        bucket: "${S3PREFIX_minio}-pihole"
        accessKey: "${S3ID_minio}"
        secretKey: "${S3KEY_minio}"
        encrKey: "${S3KEY_minio}" 
    persistence:
      config:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true                          
            src:
              enabled: true
              trigger:
                schedule: 0 3 * * *  
      dnsmasq:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true                          
            src:
              enabled: true
              trigger:
                schedule: 0 3 * * *
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                FTLCONF_dns_upstreams: ${BLOCKY_IP}
                FTLCONF_webserver_api_password: ''                           
    ingress:
        main:
          enabled: true
          ingressClassName: internal
          annotations:
            nginx.ingress.kubernetes.io/auth-url: http://authentik-http.authentik.svc.cluster.local:10230/outpost.goauthentik.io/auth/nginx
            nginx.ingress.kubernetes.io/auth-signin: https://pihole.${DOMAIN_0}/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri
            nginx.ingress.kubernetes.io/auth-response-headers: Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid
            nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Host $http_host;
          integrations:
            traefik:
              enabled: false
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
          hosts:
            - host: pihole.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix   