---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 15m
  chart:
    spec:
      chart: vaultwarden
      version: 29.3.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false    
    TZ: Europe/Brussels
    resources:
      requests:
        cpu: 10m
    credentials:
      s3:
        type: s3
        url: "${S3URL_minio}"
        bucket: "${S3PREFIX_minio}-vaultwarden"
        accessKey: "${S3ID_minio}"
        secretKey: "${S3KEY_minio}"
        encrKey: "${S3KEY_minio}"
    vaultwarden:
      allowSignups: false
      verifySignup: false
      requireEmail: false
      allowInvitation: true
      showPasswordHint: false
      enableWebVault: true
      admin:
        enabled: true
        disableAdminToken: false
        token: ${VW_TOKEN}
      smtp:
        enabled: true
        host: smtp.gmail.com
        from: ${DOMAIN_0_EMAIL}
        fromName: Balazs
        security: starttls
        port: 587
        heloName: Vault
        timeout: 15
        invalidHostname: false
        invalidCertificate: false
        user: ${DOMAIN_0_EMAIL}
        password: ${VW_SMTP_PWD}
    persistence:
      data:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true                          
            src:
              enabled: true
              trigger:
                schedule: 0 3 * * *
    cnpg:
      main:
        password: ${VAULTWARDEN_CNPG_PWD}
        cluster:
          singleNode: true
        #mode: recovery
        backups:
          enabled: true
          credentials: s3
          scheduledBackups:
            - name: daily-backup
              schedule: "30 3 0 * * *"
              backupOwnerReference: self
              immediate: true
              suspend: false
          revision: "4"
          retentionPolicy: "7d"
        recovery:
          method: object_store
          credentials: s3
          revision: "3"   
    ingress:
        main:
          enabled: true
          ingressClassName: external
          integrations:
            traefik:
              enabled: false
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
          hosts:
            - host: vault.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix             
