---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
  namespace: mealie
spec:
  interval: 15m
  chart:
    spec:
      chart: mealie
      version: 26.1.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false    
    TZ: Europe/Brussels
    resources:
      requests:
        cpu: 10m 
    credentials:
      s3:
        type: s3
        url: "${S3URL_minio}"
        bucket: "${S3PREFIX_minio}-mealie"
        accessKey: "${S3ID_minio}"
        secretKey: "${S3KEY_minio}"
        encrKey: "${S3KEY_minio}" 
    persistence:
      data:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true                          
            src:
              enabled: true
              trigger:
                schedule: 0 3 * * *
    cnpg:
      main:
        password: ${mealie_CNPG_PWD}
        cluster:
          singleNode: true
        #mode: recovery
        backups:
          enabled: true
          credentials: s3
          scheduledBackups:
            - name: daily-backup
              schedule: "30 3 0 * * *"
              backupOwnerReference: self
              immediate: true
              suspend: false
          #revision: "1"
          retentionPolicy: "7d"
        recovery:
          method: object_store
          credentials: s3
          #revision: "1" 
    ingress:
        main:
          enabled: true
          ingressClassName: internal
          integrations:
            traefik:
              enabled: false
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
          hosts:
            - host: recipes.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix   
    mealie:
      frontend:
      api:
        general:
          allow_signup: false
        smtp:
          user: "${DOMAIN_0_EMAIL}"
          password: "${mealie_SMTP_PWD}"
          host: "smtp.gmail.com"
          port: 587
          from_name: Mealie
          from_email: "${DOMAIN_0_EMAIL}"
          # TLS | SSL | NONE
          auth_strategy: TLS                         