---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: deemix
  namespace: deemix
spec:
  interval: 15m
  chart:
    spec:
      chart: deemix
      version: 13.3.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    TZ: Europe/Brussels
    resources:
      requests:
        cpu: 10m
    credentials:
      s3:
        type: s3
        url: "${S3URL_minio}"
        bucket: "${S3PREFIX_minio}-deemix"
        accessKey: "${S3ID_minio}"
        secretKey: "${S3KEY_minio}"
        encrKey: "${S3KEY_minio}"     
    persistence:
      config:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true                          
            src:
              enabled: true
              trigger:
                schedule: 0 3 * * *
      downloads:
        enabled: true
        mountPath: /downloads1
        path: /mnt/main/Media/Music/Balazs        
        server: 192.168.1.49
        type: nfs
    ingress:
        main:
          enabled: true
          ingressClassName: internal
          integrations:
            traefik:
              enabled: false
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
            nginx:
              enabled: true
              auth:
                type: "authentik"
                internalHost: "authentik-http.authentik.svc.cluster.local:10230"
                externalHost: "balazs-deemix.${DOMAIN_0}"  
          hosts:
            - host: balazs-deemix.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix